alias cat='bat'
alias df='duf'
alias ls='eza -ha --icons=always --color=always'
alias ll='eza -lha --icons=always --color=always --group-directories-first'
alias ld='eza -lhaD --icons=always --color=always'
alias lt='eza -ha --icons=always --color=always --tree'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias update='sudo cachyos-rate-mirrors && sudo pacman -Sy'
alias mkdir='mkdir -p'
alias help='tldr'
